export const BACK_DATE_WITH_ANY_FORMAT = "BACK_DATE_WITH_ANY_FORMAT";
export const NEXT_DATE_WITH_ANY_FORMAT = "NEXT_DATE_WITH_ANY_FORMAT";

export const ADD_EVENT = "ADD_EVENT";
export const CHANGE_EVENT = "CHANGE_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";

export const SET_CURRENT_DATE = "SET_CURRENT_DATE";
export const SET_CURRENT_DATE_TODAY = "SET_CURRENT_DATE_TODAY";

export const SET_TYPE_DISPLAY = "SET_TYPE_DISPLAY";
